### ISSUE TITLE
System Error when running Ganache 2.7.0 on win32

### ISSUE THREAD

**Issue by SardarShubham** [trufflesuite/ganache-ui#5291] opened 2023-02-23 19:24 UTC
PLATFORM: win32
GANACHE VERSION: 2.7.0

EXCEPTION:
```
TypeError: Cannot read property 'stack' of undefined
    at IpcMainImpl.<anonymous> (C:\Users\sardars\AppData\Local\Programs\Ganache\resources\app.asar\webpack:\src\integrations\ethereum\index.js:76:29)
    at processTicksAndRejections (internal/process/task_queues.js:93:5)
```

**Comment by jeffsmale90** [comment] 2023-03-15 00:47
Duplicate of #5296

**Closed by jeffsmale90** 2023-03-15 00:47 UTC
