### ISSUE TITLE
System Error when running Ganache 2.7.0 on darwin

### ISSUE THREAD

**Issue by Asset-Business** [trufflesuite/ganache-ui#5321] opened 2023-03-14 02:18 UTC
PLATFORM: darwin
GANACHE VERSION: 2.7.0

EXCEPTION:
```
TypeError: Cannot read property 'stack' of undefined
    at IpcMainImpl.<anonymous> (/webpack:/src/integrations/ethereum/index.js:76:29)
    at runMicrotasks (<anonymous>)
    at processTicksAndRejections (internal/process/task_queues.js:93:5)
```

**Comment by jeffsmale90** [comment] 2023-03-15 00:46
Duplicate of #5296

**Closed by jeffsmale90** 2023-03-15 00:46 UTC
